### ISSUE TITLE
thread limit exceed cause the chart museum crush

### ISSUE THREAD

**Issue by ninjadq** [goharbor/harbor-helm#1026]
the chartmuseum crushed. And logs shows thread exceed 1000 limit

and also log shows concurrent map read write issue
```

{"L":"INFO","T":"2021-07-27T20:21:40.260Z","M":"[128] Request served","path":"/voodoo/index.yaml","comment":"","latency":"10.81661ms","clientIP":"192.168.13.126","method":"GET","statusCode":200,"reqID":"f286ce45-3c49-4b52-8cf2-d4fb39b36fc8"}
{"L":"INFO","T":"2021-07-27T20:21:40.260Z","M":"[134] Request served","path":"/velero_ci/index.yaml","comment":"","latency":"9.452691ms","clientIP":"192.168.13.126","method":"GET","statusCode":200,"reqID":"3a855201-3e12-47d9-b9e4-c9dc57ac0262"}
{"L":"INFO","T":"2021-07-27T20:21:40.260Z","M":"[125] Request served","path":"/tcserver/index.yaml","comment":"","latency":"11.503788ms","clientIP":"192.168.13.126","method":"GET","statusCode":200,"reqID":"ef699eaf-7302-4814-acf5-49aeee0e60c0"}
fatal error: concurrent map read and map write

....
goroutine 334 [running]:
runtime.throw(0x1eec740, 0x21)
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000971200 sp=0xc0009711d0 pc=0x435972
runtime.mapaccess1_faststr(0x1c07880, 0xc0004fb7d0, 0xc0009276b5, 0xd, 0x1985234)
/usr/local/go/src/runtime/map_faststr.go:21 +0x43c fp=0xc000971270 sp=0xc000971200 pc=0x41470c
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getChartList(0xc0004f72c0, 0xc001af8260, 0xc0009276b5, 0xd, 0xc001a59100)
/go/src_code/pkg/chartmuseum/server/multitenant/cache.go:79 +0x93 fp=0xc000971348 sp=0xc000971270 pc=0x19824f3
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile(0xc0004f72c0, 0xc001af8260, 0xc0009276b5, 0xd, 0x4, 0xc0009276b5)
/go/src_code/pkg/chartmuseum/server/multitenant/index.go:41 +0x240 fp=0xc0009714e0 sp=0xc000971348 pc=0x1989b10
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFileRequestHandler(0xc0004f72c0, 0xc00032a4e0)
/go/src_code/pkg/chartmuseum/server/multitenant/handlers.go:89 +0xcf fp=0xc000971598 sp=0xc0009714e0 pc=0x198625f
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFileRequestHandler-fm(0xc00032a4e0)
/go/src_code/pkg/chartmuseum/server/multitenant/handlers.go:86 +0x34 fp=0xc0009715b8 sp=0xc000971598 pc=0x198cd74
helm.sh/chartmuseum/pkg/chartmuseum/router.(*Router).masterHandler(0xc0004f7180, 0xc00032a4e0)
/go/src_code/pkg/chartmuseum/router/router.go:242 +0x16f fp=0xc000971680 sp=0xc0009715b8 pc=0x1020ecf
helm.sh/chartmuseum/pkg/chartmuseum/router.(*Router).masterHandler-fm(0xc00032a4e0)
/go/src_code/pkg/chartmuseum/router/router.go:205 +0x34 fp=0xc0009716a0 sp=0xc000971680 pc=0x10220b4
github.com/gin-gonic/gin.(*Context).Next(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc0009716c0 sp=0xc0009716a0 pc=0xfb72db
github.com/zsais/go-gin-prometheus.(*Prometheus).HandlerFunc.func1(0xc00032a4e0)
/go/pkg/mod/github.com/zsais/go-gin-prometheus@v0.1.0/middleware.go:364 +0xcf fp=0xc000971768 sp=0xc0009716c0 pc=0x101d74f
github.com/gin-gonic/gin.(*Context).Next(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000971788 sp=0xc000971768 pc=0xfb72db
github.com/gin-contrib/size.RequestSizeLimiter.func1(0xc00032a4e0)
/go/pkg/mod/github.com/gin-contrib/size@v0.0.0-20200226145816-24aa35f64b9f/size.go:88 +0xa5 fp=0xc0009717b0 sp=0xc000971788 pc=0xfdf795
github.com/gin-gonic/gin.(*Context).Next(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc0009717d0 sp=0xc0009717b0 pc=0xfb72db
helm.sh/chartmuseum/pkg/chartmuseum/router.requestWrapper.func1(0xc00032a4e0)
/go/src_code/pkg/chartmuseum/router/middleware.go:48 +0xf9 fp=0xc000971950 sp=0xc0009717d0 pc=0x1021719
github.com/gin-gonic/gin.(*Context).Next(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc000971970 sp=0xc000971950 pc=0xfb72db
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 +0x60 fp=0xc0009719b0 sp=0xc000971970 pc=0xfca930
github.com/gin-gonic/gin.(*Context).Next(0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b fp=0xc0009719d0 sp=0xc0009719b0 pc=0xfb72db
github.com/gin-gonic/gin.serveError(0xc00032a4e0, 0x194, 0x3219160, 0x12, 0x12)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:439 +0x38 fp=0xc000971a28 sp=0xc0009719d0 pc=0xfc1028
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0005d03c0, 0xc00032a4e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:432 +0x3e0 fp=0xc000971bb0 sp=0xc000971a28 pc=0xfc0cc0
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0005d03c0, 0x2302640, 0xc000928620, 0xc0053d2700)
/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x14d fp=0xc000971be8 sp=0xc000971bb0 pc=0xfc065d
net/http.serverHandler.ServeHTTP(0xc00026a0e0, 0x2302640, 0xc000928620, 0xc0053d2700)
/usr/local/go/src/net/http/server.go:2836 +0xa3 fp=0xc000971c18 sp=0xc000971be8 pc=0x6f48a3
net/http.(*conn).serve(0xc00048fea0, 0x2309e00, 0xc002b91040)
/usr/local/go/src/net/http/server.go:1924 +0x86c fp=0xc000971fc8 sp=0xc000971c18 pc=0x6f020c
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000971fd0 sp=0xc000971fc8 pc=0x4662a1
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2962 +0x35c

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f37ec5e9e00, 0x72, 0x0)
/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00017ca98, 0x72, 0x0, 0x0, 0x1ebbec8)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00017ca80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00017ca80, 0xa007be7bd81c614a, 0x0, 0xa007be7bd81c614a)
/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0004fcfc0, 0x61006ad4, 0xc0000d3340, 0x4c8656)
/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0004fcfc0, 0xc0000d3390, 0x18, 0xc000000180, 0x6f4d4c)
/usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc00026a0e0, 0x2302380, 0xc0004fcfc0, 0x0, 0x0)
/usr/local/go/src/net/http/server.go:2930 +0x25d
net/http.(*Server).ListenAndServe(0xc00026a0e0, 0x3, 0xc00089d618)
/usr/local/go/src/net/http/server.go:2859 +0xb7
helm.sh/chartmuseum/pkg/chartmuseum/router.(*Router).Start(0xc0004f7180, 0x270f)
/go/src_code/pkg/chartmuseum/router/router.go:195 +0x6cd
helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).Listen(0xc0004f72c0, 0x270f)
/go/src_code/pkg/chartmuseum/server/multitenant/server.go:148 +0x39
main.cliHandler(0xc0005f2000)
/go/src_code/cmd/chartmuseum/main.go:108 +0xd28
github.com/urfave/cli.HandleAction(0x1b51e00, 0x1f978a0, 0xc0005f2000, 0xc00051a3c0, 0x0)
/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.(*App).Run(0xc000610000, 0xc00003c1d0, 0x1, 0x1, 0x0, 0x0)
/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5dd
main.main()
/go/src_code/cmd/chartmuseum/main.go:52 +0x1c4

goroutine 6 [chan receive]:
github.com/baidubce/bce-sdk-go/util/log.NewLogger.func1(0xc00007e720)
/go/pkg/mod/github.com/baidubce/bce-sdk-go@v0.9.7/util/log/logger.go:362 +0x143
created by github.com/baidubce/bce-sdk-go/util/log.NewLogger
/go/pkg/mod/github.com/baidubce/bce-sdk-go@v0.9.7/util/log/logger.go:359 +0xd7
........

```

**Comment by ninjadq** [comment]
https://github.com/goharbor/harbor-helm/pull/1028
