### ISSUE TITLE
Jobservice exid code 401: Failed on load rest config

### ISSUE THREAD

**Issue by EsDmitrii** [goharbor/harbor-helm#1622]
Hi!
Faced the issue:
```
2023-10-20T15:29:43Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: http://harbor-core:80/api/v2.0/internalconfig
2023-10-20T15:29:43Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"only internal service is allowed to call this API"}]}
, url:http://harbor-core:80/api/v2.0/internalconfig
panic: failed to load configuration, error: failed to load rest config

goroutine 1 [running]:
main.main()
	/harbor/src/jobservice/main.go:44 +0x3ee
```
From time to time jobservice restarts with error above.
Found couple closed issues here in git related to this problem but they are old ones (closed about 1-2 years ago) and there no any solution.
Deployed using helm chart v1.13.0
Harbor Version v2.9.0-6d1ad65c

**Comment by zyyw** [comment]
There are some new discussion about this issue here:
* https://github.com/goharbor/harbor/issues/12573

**Comment by zyyw** [comment]
Could you please paste the log of core, redis, db? Is db pod up and running?

**Comment by EsDmitrii** [comment]
Hi!
Sorry for the late response.
I use HA external Postgres outside k8s. It is up and running.
Redis+Sentinel also up and running inside k8s. Without restarts, etc.
The same for core
I'll see the https://github.com/goharbor/harbor/issues/12573
Thanks

**Comment by ajaythecoder** [comment]
Hello, Any solution for this?
