### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by GYICN** [goharbor/harbor-helm#187]
[root@kubemaster harbor-helm]# kubectl logs -n harbor harbor-v1-harbor-core-55b867b98d-4sv5q 
2019-03-14T06:50:55Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: http_auth
2019-03-14T06:50:55Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: db_auth
2019-03-14T06:50:55Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: ldap_auth
2019-03-14T06:50:55Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: uaa_auth
2019-03-14T06:50:55Z [DEBUG] [init.go:37]: topic StartReplication is subscribed
2019-03-14T06:50:55Z [DEBUG] [init.go:37]: topic OnPush is subscribed
2019-03-14T06:50:55Z [DEBUG] [init.go:37]: topic OnDeletion is subscribed
2019-03-14T06:50:55Z [INFO] Config path: /etc/core/app.conf
2019-03-14T06:50:55Z [INFO] initializing configurations...
2019-03-14T06:50:55Z [INFO] key path: /etc/core/key
2019-03-14T06:50:55Z [INFO] init secret store
2019-03-14T06:50:55Z [INFO] init project manager based on deploy mode
2019-03-14T06:50:55Z [INFO] initializing the project manager based on local database...
2019-03-14T06:50:55Z [INFO] configurations initialization completed
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goharbor/harbor/src/core/config.ExtURL(0xd1ca60, 0xc4203bed80, 0xe1e373, 0x8)
	/go/src/github.com/goharbor/harbor/src/core/config/config.go:247 +0x14a
github.com/goharbor/harbor/src/core/service/token.InitCreators()
	/go/src/github.com/goharbor/harbor/src/core/service/token/creator.go:53 +0x1da
main.main()
	/go/src/github.com/goharbor/harbor/src/core/main.go:91 +0x1ea

I don't know why.

**Comment by ywk253100** [comment]
Did you set the `externalURL` https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L76? It should be like `https://hostname`

**Comment by DarkRider1768** [comment]
I'm running into this exact same issue behind MetalLB. There isn't anything in the instructions for configuring this behind a L4 Load Balancer. I've tried:

Setting it to the hostname assigned to the IP address of the service (as required by the chart).
Setting it to the IP address of the service.
Leaving the configuration for it blank.
Deploying the service with the default option.

Can I get some assistance getting this configured? Harbor Core (and by extension, Job Service) are failing to deploy with the same error as originally posted.
