### ISSUE TITLE
Harbor-UI failing on empty Clair DB connection string

### ISSUE THREAD

**Issue by mikelnick** [goharbor/harbor-helm#28]
I am trying to stand harbor's parts up for the first time in kubernetes and puzzled by an error the harbor-UI is throwing.  The logs are essentially saying the connection string is empty - I'm just not clear where I would change/add env variables and which ones.  I have the admin server and clair running in the cluster already too to make things a bit more unclear.

I'm using `dev` for all except the UI and jobservice, for which I'm using `v1.6.0`
error:
```
2018-09-11T22:55:06Z [INFO] API controller for chart repository server is successfully initialized
2018-09-11T22:55:06Z [INFO] Policy scheduler start at 2018-09-11T22:55:06Z
[ORM]2018/09/11 22:55:06 register db Ping `clair-db`, pq: database "sslmode=disable" does not exist
2018-09-11T22:55:06Z [FATAL] [main.go:128]: failed to initialize clair database: register db Ping `clair-db`, pq: database "sslmode=disable" does not exist
```

**Comment by ywk253100** [comment]
@mikelnick Please use the chart on branch 0.3.0 which is using Harbor 1.6.0 images.

**Comment by mikelnick** [comment]
Thanks @ywk253100 .  Is there a way with env variables to direct the use of redis on aws elasticache?  Getting `read: connection reset by peer` because it appears I'm not setting redis.external.enabled correctly.

**Comment by mikelnick** [comment]
I'm not able to use helm with our cluster set up so I have reworked a lot of the kube dpl and secrets to do my bidding.  Seems like this is the little bit I can't overcome without some help.

**Comment by ywk253100** [comment]
So what's your problem now? The database or the Redis? 
Can you clean up your environment by deleting the Harbor release and all PV/PVC used by Harbor and re-install again?
If you get errors, we can debug and fix them one by one.

**Comment by mikelnick** [comment]
The UI and jobservice cannot connect to redis in the logs.  I realized I'm using just one redis cluster though and I probably need a different one for each component that requires it - ui, jobservice and registry.  I was thinking I needed to be able to declare the redis cluster external via an environment variable the same way that's done with harbor config/values.yml.  

Error from JobService
```
kubectl logs harbor-jobservice-pod -n mynamespace
2018-09-13T02:21:24Z [INFO] Registering database: type-PostgreSQL xxx-rds.amazonaws.com port-5432 databse-harbor sslmode-"disable"
2018-09-13T02:21:24Z [INFO] Register database completed
2018-09-13T02:22:59Z [FATAL] [service_logger.go:73]: Failed to load and run worker pool: connect to redis server timeout: write tcp 192.122.33.22:35626->10.111.11.11:6379: use of closed network connection````

Error from UI:
```
2018-09-13T02:18:35Z [INFO] Register database completed
2018-09-13T02:18:35Z [INFO] User id: 1 already has its encrypted password.
2018-09-13T02:18:35Z [ERROR] [cache.go:168]: Failed to initialize redis cache: read tcp 192.168.16.82:58214->10.249.22.75:6379: read: connection reset by peer
2018-09-13T02:18:35Z [INFO] No cache is enabled for chart caching
2018-09-13T02:18:35Z [DEBUG] [chart_repository.go:419]: Chart storage server is set to https://chartmuseum-dns
2018-09-13T02:18:35Z [INFO] API controller for chart repository server is successfully initialized
2018-09-13T02:18:35Z [INFO] Policy scheduler start at 2018-09-13T02:18:35Z
2018-09-13T02:18:35Z [ERROR] [main.go:162]: Failed to parse SYNC_REGISTRY: strconv.ParseBool: parsing "": invalid syntax
2018-09-13T02:18:35Z [INFO] Because SYNC_REGISTRY set false , no need to sync registry 
2018-09-13T02:18:35Z [INFO] Init proxy
panic: read tcp 192.168.16.82:58216->10.249.22.75:6379: read: connection reset by peer
goroutine 1 [running]:
github.com/vmware/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
	/go/src/github.com/vmware/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
github.com/vmware/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/go/src/github.com/vmware/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
main.main()
	/go/src/github.com/vmware/harbor/src/ui/main.go:177 +0x869
```

**Comment by ywk253100** [comment]
The Harbor components can share the same Redis instance configured in the values.yaml. The error you got seems related to your network.
