### ISSUE TITLE
After upgrading helm chart from 1.4.3 to 1.5.0, harbor-core container fails liveness probes

### ISSUE THREAD

**Issue by Bak3y** [goharbor/harbor-helm#765]
Debug logs enabled on the container:

```
2020-10-15T16:17:29Z [INFO] [/core/main.go:162]: initializing configurations...
2020-10-15T16:17:29Z [INFO] [/core/config/config.go:84]: key path: /etc/core/key
2020-10-15T16:17:29Z [INFO] [/core/config/config.go:61]: init secret store
2020-10-15T16:17:29Z [INFO] [/core/config/config.go:64]: init project manager
2020-10-15T16:17:29Z [INFO] [/core/config/config.go:96]: initializing the project manager based on local database...
2020-10-15T16:17:29Z [INFO] [/core/main.go:164]: configurations initialization completed
2020-10-15T16:17:29Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-stg-harbor.fqdn-redacted.com port-5432 database-registry sslmode-"disable"
2020-10-15T16:17:29Z [INFO] [/common/dao/base.go:70]: Register database completed
2020-10-15T16:17:29Z [DEBUG] [/migration/migration.go:47]: current database schema version: 40
2020-10-15T16:17:29Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
2020-10-15T16:17:29Z [INFO] [/common/dao/pgsql.go:130]: No change in schema, skip.
2020-10-15T16:17:29Z [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:199]: Closing source and database
2020-10-15T16:17:29Z [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:199]: Closing source and database
2020-10-15T16:17:29Z [INFO] [/migration/migration.go:58]: Abstracting artifact data to DB...
2020-10-15T16:17:29Z [DEBUG] [/migration/migration.go:64]: current data version: 30
2020-10-15T16:17:29Z [INFO] [/migration/migration.go:67]: No need to abstract artifact data. Skip
2020-10-15T16:17:29Z [INFO] [/core/main.go:81]: User id: 1 already has its encrypted password.
2020-10-15T16:17:29Z [INFO] [/core/main.go:244]: Removing Trivy scanner
2020-10-15T16:17:29Z [INFO] [/core/main.go:258]: Removing Clair scanner
2020-10-15T16:17:29Z [DEBUG] [/lib/redis/redisclient.go:66]: get redis pool:CommonRedisredis://192.168.0.2:6379/2?idle_timeout_seconds=30
2020-10-15T16:17:29Z [DEBUG] [/replication/replication.go:92]: the replication initialization completed
2020-10-15T16:17:29Z [INFO] [/core/main.go:202]: initializing notification...
2020-10-15T16:17:29Z [INFO] [/pkg/notification/notification.go:47]: notification initialization completed
2020-10-15T16:17:29Z [INFO] [/core/main.go:221]: Version: v2.1.0, Git commit: a3eca103
```

Events from the harbor-core pod:

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  17m                   default-scheduler  Successfully assigned harbor/harbor-harbor-core-85796cdd97-dbcbv to ip-10-41-33-155.ec2.internal
  Normal   Killing    16m (x2 over 17m)     kubelet            Container core failed liveness probe, will be restarted
  Normal   Pulled     15m (x3 over 17m)     kubelet            Container image "goharbor/harbor-core:v2.1.0" already present on machine
  Normal   Created    15m (x3 over 17m)     kubelet            Created container core
  Normal   Started    15m (x3 over 17m)     kubelet            Started container core
  Warning  Unhealthy  15m (x10 over 17m)    kubelet            Readiness probe failed: Get http://100.96.60.158:8080/api/v2.0/ping: dial tcp 100.96.60.158:8080: connect: connection refused
  Warning  Unhealthy  7m19s (x16 over 17m)  kubelet            Liveness probe failed: Get http://100.96.60.158:8080/api/v2.0/ping: dial tcp 100.96.60.158:8080: connect: connection refused
  Warning  BackOff    2m18s (x44 over 12m)  kubelet            Back-off restarting failed container
```

Pod side logs from an attempted curl:
```
 kubectl port-forward deployment/harbor-harbor-core 8080:8080


Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
E1015 11:16:04.754000   57699 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 3cb8e5ad92653d350eb125a9cfa9ad696ab1f728cee951ab58656a631be9b089, uid : exit status 1: 2020/10/15 16:16:04 socat[3916267] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8080
E1015 11:16:12.178365   57699 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 3cb8e5ad92653d350eb125a9cfa9ad696ab1f728cee951ab58656a631be9b089, uid : exit status 1: 2020/10/15 16:16:12 socat[3916331] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```

Client side logs from an attempted curl:
```
 curl -vvv http://localhost:8080/api/v2.0/ping
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /api/v2.0/ping HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.72.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

I don't see anything in any logs anywhere that show why this is failing.

**Comment by wesleyorama2** [comment]
Continuing to trouble shoot with @Bak3y, extending the health-check initial wait allowed this error to bubble up:
```
2020-10-15T16:53:55Z [INFO] [/core/main.go:221]: Version: v2.1.0, Git commit: a3eca103
panic: dial tcp 192.168.0.2:6379: connect: connection timed out

goroutine 1 [running]:
github.com/astaxie/beego.initBeforeHTTPRun()
	/harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20c
github.com/astaxie/beego.RunWithMiddleWares(0x0, 0x0, 0xc000835d10, 0xa, 0xa)
	/harbor/src/vendor/github.com/astaxie/beego/beego.go:77 +0x26
main.main()
	/harbor/src/core/main.go:222 +0x6a3
```

**Comment by Bak3y** [comment]
Turns out, there was a breaking change to the expected values.yaml file in 1.5.0, related to this commit: https://github.com/goharbor/harbor-helm/commit/0290094e555bf85473106a8c12635c506f744193

We're connecting to an external redis server that was previously set as redis.external.host and redis.external.port, and now has to be set as redis.external.addr.

This should have been noted in either the release notes as a breaking change, or in the upgrade document.

**Comment by matthewhembree** [comment]
I spent a lot of time on this. Github release notes would be a good place to call out breaking changes. That's where I typically look for upgrade tips.

Trivy will also fail liveness probes without any logs. I was able to focus on this (Trivy) because I scaled down the deployments. I accidentally decided to look at the Trivy secret where the new Redis URL of `192.168.0.2:6379` was.
