### ISSUE TITLE
Jobservice CrashLoopBackOff

### ISSUE THREAD

**Issue by mohaijiang** [goharbor/harbor-helm#82]
I tried use this chart to install harbor , but the Jobservice pod cannot startup.

What wrong with it?

Here is my harbor info:
```
[root@master harbor-helm]# kubectl -n harbor-dev get pvc
NAME                                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-harbor-dev-harbor-redis-0               Bound     pvc-29181d68-e3cb-11e8-86c1-fa163eb28327   1Gi        RWO            rbd            12m
database-data-harbor-dev-harbor-database-0   Bound     pvc-290d3930-e3cb-11e8-86c1-fa163eb28327   1Gi        RWO            rbd            12m
harbor-dev-harbor-chartmuseum                Bound     pvc-289b297a-e3cb-11e8-86c1-fa163eb28327   5Gi        RWO            rbd            12m
harbor-dev-harbor-jobservice                 Bound     pvc-289d7b74-e3cb-11e8-86c1-fa163eb28327   1Gi        RWO            rbd            12m
harbor-dev-harbor-registry                   Bound     pvc-289ef921-e3cb-11e8-86c1-fa163eb28327   50Gi       RWO            rbd            12m
[root@master harbor-helm]# kubectl -n harbor-dev get po 
NAME                                               READY     STATUS             RESTARTS   AGE
harbor-dev-harbor-adminserver-5f5bb8479-gtk6c      1/1       Running            3          12m
harbor-dev-harbor-chartmuseum-7865bbfc46-fkblk     1/1       Running            0          12m
harbor-dev-harbor-clair-568d6cc674-7dtsb           1/1       Running            2          12m
harbor-dev-harbor-core-6d6d659975-92gzp            1/1       Running            3          12m
harbor-dev-harbor-database-0                       1/1       Running            0          12m
harbor-dev-harbor-jobservice-845c69c5c-s5lcw       0/1       CrashLoopBackOff   6          12m
harbor-dev-harbor-notary-server-668cc9b786-khdkn   1/1       Running            0          12m
harbor-dev-harbor-notary-signer-657f4cbfdd-mnkhg   1/1       Running            0          12m
harbor-dev-harbor-portal-67c958994c-hr2ls          1/1       Running            0          12m
harbor-dev-harbor-redis-0                          1/1       Running            0          12m
harbor-dev-harbor-registry-68b5c6c88f-sfzmm        2/2       Running            0          12m

[root@master harbor-helm]# kubectl -n harbor-dev logs -f harbor-dev-harbor-jobservice-845c69c5c-s5lcw
panic: load configurations error: missing logger config of job service


goroutine 1 [running]:
main.main()
	/go/src/github.com/goharbor/harbor/src/jobservice/main.go:41 +0x265


```

**Comment by ywk253100** [comment]
The configuration file of `Jobservice` is changed by the PR https://github.com/goharbor/harbor/pull/6215 merged yesterday. Will do the corresponding changes in Harbor chart soon.

**Comment by mohaijiang** [comment]
@ywk253100 thanks for help , but the chart I used is the latest master branch, an hour ago. PR goharbor/harbor#6215 should be merged.

**Comment by ywk253100** [comment]
Should be fixed, try again.

**Comment by ywk253100** [comment]
Are you using the latest images? Set `imagePullPolicy ` to `Always`

**Comment by Timer** [comment]
Newest version isn't in a crash loop, but suffering from 401s:
```
2018-11-09T13:31:08.589679000Z 2018-11-09T13:31:08Z [DEBUG] [sweeper_controller.go:89]: Sweeper *sweeper.FileSweeper is under working
2018-11-09T13:31:08.589952000Z 2018-11-09T13:31:08Z [INFO] 0 outdated log entries are sweepped by sweeper *sweeper.FileSweeper
2018-11-09T13:31:08.592072000Z 2018-11-09T13:31:08Z [ERROR] [context.go:85]: Job context initialization error: http error: code 401, message Unauthorized
2018-11-09T13:31:08.592545000Z 2018-11-09T13:31:08Z [INFO] Retry in 9 seconds
2018-11-09T13:31:17.593604000Z 2018-11-09T13:31:17Z [ERROR] [context.go:85]: Job context initialization error: http error: code 401, message Unauthorized
2018-11-09T13:31:17.594001000Z 2018-11-09T13:31:17Z [INFO] Retry in 13 seconds
2018-11-09T13:31:30.594249000Z 2018-11-09T13:31:30Z [ERROR] [context.go:85]: Job context initialization error: http error: code 401, message Unauthorized
2018-11-09T13:31:30.594782000Z 2018-11-09T13:31:30Z [INFO] Retry in 19 seconds
2018-11-09T13:31:49.595193000Z 2018-11-09T13:31:49Z [ERROR] [context.go:85]: Job context initialization error: http error: code 401, message Unauthorized
2018-11-09T13:31:49.595747000Z 2018-11-09T13:31:49Z [INFO] Retry in 29 seconds
```

**Comment by ywk253100** [comment]
@Timer Make sure the chart and images are all the latest versions, it can't be that. Or you can use the chart in 0.3.0 branch, the master code is under development, it may be broken sometimes.

**Comment by mohaijiang** [comment]
Upgrade to latest repository and set image imagePullPolicy to Always resolve this issue.
```
[root@master harbor-helm]# kubectl -n harbor-dev get po
NAME                                               READY     STATUS    RESTARTS   AGE
harbor-dev-harbor-adminserver-74d84798f-mn6gx      1/1       Running   1          3m
harbor-dev-harbor-chartmuseum-7f7f749c76-nf96g     1/1       Running   0          3m
harbor-dev-harbor-clair-86774d7c68-28fj8           1/1       Running   1          3m
harbor-dev-harbor-core-5998bc8cdf-p9p97            1/1       Running   1          3m
harbor-dev-harbor-database-0                       1/1       Running   0          3m
harbor-dev-harbor-jobservice-647f9f6f45-z2nk8      1/1       Running   0          3m
harbor-dev-harbor-notary-server-7bc9cc6c55-m7472   1/1       Running   0          3m
harbor-dev-harbor-notary-signer-79699d6c69-xr4mw   1/1       Running   0          3m
harbor-dev-harbor-portal-7f5dff98cc-9xjmg          1/1       Running   0          3m
harbor-dev-harbor-redis-0                          1/1       Running   0          3m
harbor-dev-harbor-registry-796b9ffb89-zcnww        2/2       Running   0          3m

```
